#184 - User authentication
blumilksoftware/internships pull request #185
Opened 2022-08-31 11:13 UTC by sbanasiak

The site now has options for login, registration, password reset and email verification. The existing views have been adjusted for authentication functionality and new views have been created - for email verification and password reset.

![image](https://user-images.githubusercontent.com/92038757/187664564-f7a40990-3bf7-4c83-a078-b8c21c64bb54.png)

When logging in, the user can remember his session and after logging in, user can log out by clicking a button in the navigation bar. 

![image](https://user-images.githubusercontent.com/92038757/187665897-cc1805b3-d66f-44b8-b793-bbb4cc36401a.png)

Login and email address confirmation are now required to submit a new company - there is automatic redirect to the login/email confirmation page.

![image](https://user-images.githubusercontent.com/92038757/187665309-bf76e949-3e1d-4c6d-8ea8-05992f946315.png)

Routes needed for authentication have been created and a helper package [tighten/ziggy](https://github.com/tighten/ziggy) which provides a JavaScript `route()` helper function that works like Laravel's has been installed.

Closes #184 

Pull request also closes #183 - added Laravel error translations and rewritten the localization keys to snake_case.

2022-08-31 11:58 UTC, kamilpiech97 requested changes

2022-08-31 11:58 UTC, kamilpiech97 commented on backend/app/Http/Controllers/Auth/PasswordResetLinkController.php
> +        ]);
The same as above.

2022-08-31 11:58 UTC, kamilpiech97 commented on backend/app/Http/Controllers/Auth/RegisteredUserController.php
> +        ]);
The same as above.

2022-08-31 11:58 UTC, kamilpiech97 commented on frontend/js/Pages/Error.vue
>  });
Move setup section above of the template element - setup section is above of the template in components.

2022-08-31 11:58 UTC, kamilpiech97 commented on frontend/js/Pages/Auth/VerifyEmail.vue
> +</script>
Move to the top of file.

2022-09-01 06:08 UTC, EwelinaLasowy reviewed
By default. the site is in English - maybe we should think of determining the current locale?

2022-09-01 06:23 UTC, sbanasiak commented on frontend/js/Pages/Auth/ResetPassword.vue
> +<script setup>
Fixes to the translation of the site and other elements will be included in a separate localization pull request.

2022-09-01 07:17 UTC, kamilpiech97 approved these changes

2022-09-01 07:17 UTC, EwelinaLasowy approved these changes

2022-09-01 07:18 UTC, merged