#28 - landing page
blumilksoftware/internships pull request #39
Opened 2021-07-14 07:17 UTC by brzozka

This PR should close #28 

Color scheme/pictures are not final, so they can be changed later on. For now  buttons redirect user to empty home page, cause there is no other page yet. Funcionality will be implemented later into the project.

2021-07-14 07:30 UTC, krzysztofrewak commented
Btw, the good practice would be adding some screenshots of your work.

2021-07-14 07:42 UTC, brzozka commented
I forgot to add the screenshot of the page, and my laptop started lagging, that's why it took so long, but here it is.
![image](https://user-images.githubusercontent.com/39692087/125582992-e4e3b705-ba12-4077-9b59-16765c59ff70.png)

2021-07-14 08:25 UTC, krzysztofrewak commented
Maybe something like this would be better? Or at least more consistent?

![image](https://user-images.githubusercontent.com/10898728/125589492-8f41e320-8d5f-46e3-9d1f-d72243471bb9.png)

2021-07-15 08:17 UTC, mtracz requested changes

2021-07-15 08:17 UTC, mtracz commented on frontend/main.js
> +import "./assets/tailwind.css";
Please use `@` alias instead of `./`

2021-07-15 08:21 UTC, brzozka commented on frontend/main.js
> +import "./assets/tailwind.css";
Oh yeah, I forgot about it, thanks

2021-07-15 11:35 UTC, brzozka commented
Something like this?
![image](https://user-images.githubusercontent.com/39692087/125781684-cee31482-710f-4765-aa7b-c01e3868ed7f.png)

2021-07-15 12:45 UTC, mtracz approved these changes

2021-07-15 12:51 UTC, krzysztofrewak approved these changes

2021-07-15 12:59 UTC, EwelinaLasowy approved these changes

2021-07-15 13:03 UTC, merged