#69 - implement company cache to filters
blumilksoftware/internships pull request #79
Opened 2021-07-28 10:49 UTC by plencka

It should close #69.

Change intended to make searching light-weight, to remove the need to parse company data to find matching filters.

2021-07-28 14:09 UTC, mtracz requested changes

2021-07-28 14:09 UTC, mtracz commented on backend/Factories/DataFactory.php
> +                $preparedEntry = $this->processEntry($jsonID, $this->validate($jsonID, $entry));
Please rename to`$jsonId`

2021-07-28 14:09 UTC, mtracz commented on backend/Factories/CompanyDataFactory.php
> +            array_push($tagIDs, $tagCollector->collectAndGetID($tag, $entryId));
Please rename to `$tagIds`

2021-07-29 06:23 UTC, krzysztofrewak approved these changes

2021-07-29 06:36 UTC, mtracz approved these changes

2021-07-29 06:51 UTC, brzozka approved these changes

2021-07-29 07:52 UTC, merged