#78 - match filter tags with specialization
blumilksoftware/internships pull request #88
Opened 2021-07-29 12:45 UTC by plencka

This PR should close #78.

Tags are now matched to specializations. 
Intended for showing only tags related to specialization during their selection.

2021-07-30 06:45 UTC, mtracz approved these changes

2021-07-30 08:35 UTC, kamilpiech97 requested changes

2021-07-30 08:35 UTC, kamilpiech97 commented on backend/Services/DataValidator.php
>          int $entryID,
```suggestion
        int $entryId,
```

2021-08-02 10:02 UTC, kamilpiech97 approved these changes

2021-08-02 10:05 UTC, krzysztofrewak approved these changes

2021-08-03 11:55 UTC, brzozka approved these changes

2021-08-03 11:56 UTC, merged